version: 0.0
os: linux

files:
  files:
  - source: /devops.html   <-- Change this to match your actual file
    destination: /var/www/html/
    

hooks:
  BeforeInstall:
    

  ApplicationStart:
    
